### PR TITLE
Add viewport html meta tag for mobile devices

### PR DESCRIPTION
**Pull request by tong**

### CODE REVIEW

**Comment by markknol** [comment]
Does this make everything look good on mobile?

**Comment by tong** [comment]
Well not really :) but it removes the annoying zoom on pinch.
No effect on desktop devices.

**Comment by tong** [comment]
Ups. just tested and this isn't good … the sidebar is in conflict with the layout.
Gonna come back on this later.

**Comment by markknol** [comment]
Thanks! I like the idea of making it more mobile friendly so any help there is welcome!

**Pull request closed without merging**
