### PR TITLE
Fix the check for minimum node version

### PR DESCRIPTION
**Pull request by ninjamuffin99**
The check for the minimum supported node version would check if you had 8.x.x or above, AND if the minor version was x.10.x, meaning if you had say 9.0.0, of node, it would actually be an invalid node version, since x.0.x is smaller than x.10.x, the minor version would invalidate the node version, and it'd revert to the neko version of dox

This PR updates the check so that it'd only check the minor version if you are on node v8 exactly, anything below is invalidated otherwise

### CODE REVIEW

**Comment by Simn** [comment]
This looks more awkward than it has to, shouldn't it be something along the lines of `parts[0] > 8 || parts[0] == 8 && parts[1] >= 10`?

**Comment by ninjamuffin99** [comment]
thatd work too, i suppose it was choice between doing a oneliner, or separating out the way i did. But this oneliner looks nice and tidy I will use that!

**Comment by Simn** [comment]
Thanks! I suppose we should update run.n again too.

**Comment by ninjamuffin99** [comment]
doh! I knew i was forgetting something lol

**Pull request merged**
