### PR TITLE
Mention the wiki in README.md

### PR DESCRIPTION
**Pull request by markknol**
Because it useful contains info.

### CODE REVIEW

**Comment by Gama11** [comment]
Huh, I didn't even realize there was one. :+1:

**Comment by Simn** [comment]
I didn't quite realize that either, which is all the more funny because apparently I originally wrote that...

**Comment by Gama11** [comment]
Doesn't help that even if you happen to click the Wiki button, it takes you to the standard / empty "Welcome to the dox wiki!" home page.

**Comment by markknol** [comment]
I linked it to that page but maybe its more clear to put it in the readme instead? It is useful info.

**Comment by Simn** [comment]
The wiki is a good place for it but it might make sense to just move it to the wiki entry page.

**Comment by markknol** [comment]
Good for me. Ill update this soon.

**Pull request merged**
