### PR TITLE
Breadcrumb

### PR DESCRIPTION
**Pull request by markknol**
Displays full inheritance tree.

image

### CODE REVIEW

**Comment by Simn** [comment]
Can we use a directional separator like `>` or `->`?

**Comment by markknol** [comment]
I dont know if that might be confusing since something can become `Value<Float> > Value<T>`

**Comment by Simn** [comment]
Well, we need something that doesn't make it look like multiple inheritance.

**Comment by markknol** [comment]
maybe a raquo ? `»`

**Comment by Simn** [comment]
That should do

**Comment by markknol** [comment]
image

I found a nice arrow.

**Pull request merged**
